// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0HbYxkKxGcIDSwvmSZKxcPlJ9gz0MsCQ',
    appId: '1:545378708614:web:055b0556a40a6ee326f507',
    messagingSenderId: '545378708614',
    projectId: 'recent-dishes-app',
    authDomain: 'recent-dishes-app.firebaseapp.com',
    storageBucket: 'recent-dishes-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmnjOXfsLv_nl0L4tEf6quJXNaUxkVaM',
    appId: '1:545378708614:ios:80562c41f86ac6be26f507',
    messagingSenderId: '545378708614',
    projectId: 'recent-dishes-app',
    storageBucket: 'recent-dishes-app.appspot.com',
    iosBundleId: 'com.example.recentDishesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0HbYxkKxGcIDSwvmSZKxcPlJ9gz0MsCQ',
    appId: '1:545378708614:web:7ab73310c86fe9bf26f507',
    messagingSenderId: '545378708614',
    projectId: 'recent-dishes-app',
    authDomain: 'recent-dishes-app.firebaseapp.com',
    storageBucket: 'recent-dishes-app.appspot.com',
  );

}